language: python

matrix:
  include:
  - python: 3.3
    dist: trusty
  - python: 3.4
    dist: trusty
  - python: 3.5
    dist: xenial
  - python: 3.6
    dist: xenial
  - python: 3.7
    dist: xenial

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - pycodestyle libconnect client server
  - pytest --verbose --capture=no libconnect client server
  - pip install .